Add missing overrides to the generated classes
This solves error: class 'SomeClass' is not abstract and does not implement abstract member public abstract fun

This is due to what typescript and kotlin treats as override